### ISSUE TITLE
Should do some change

### ISSUE THREAD

**Issue by Hugefatsheep** [reenberg/CTFd_FirstBlood#1]
In latest CTFd, it change the name of CTFd_DynamicValueChallenge, so when you import DynamicValueChallenge will make a mistake. So you should use "from CTFd.plugins.dynamic_challenges import DynamicValueChallenge".
And there is another one that I dont know how to fix your code. In __init__.py, line 105, the code "chal_cls.ee.on("challenge.onPreSolve", on_challenge_pre_solve)" has a AttributeError: type object 'CTFdStandardChallenge' has no attribute 'ee'. I have no idea how to fix it.

**Comment by reenberg** [comment]
Sorry for the late comment.  was enjoying holliday :)

This challenge plugin relies on the still unmerged, and even uncommented/debated, PR from NOV 2017 :-1:  CTFd/CTFd#464.  The `ee` is a reference to the EventEmitter that is implemented in the PR, so without that, you won't be able to use this plugin.

I don't see myself having the time in the foreseeable future to try and fix this challenge plugin to work with the newest CTFd, unless they decide to merge the PR.  I haven't been using CTFd in about 2 years, well about since I created that PR, and I don't see myself using it again anytime soon.

It would be nice if CTFd wanted to adopt any of the plugins that I made, so that they won't end up stranded, as they are now.

If you want to make a PR with changes to the DynamicValueChallenge, then I will happily accept it, but it would it would still leave the other issue.  
"Sadly" this plugin relies heavily on the events to know when the first correct solution is submitted, so you won't be able to remove that part of the code.
